version: '3.5'

networks:
  seedco-network:
    name: seedco_default

volumes:
    postgres_data:
    pgadmin-data:
    
services:

#  main-nginx:
#    image: nginx:alpine
#    container_name: main.accutrak.dev
#    volumes:
#      - ./Infra/nginx/dev_conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
#    ports:
#      - "80:80"
#    restart: always
#    networks:
#      - accutrak-network
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "50M"
#        max-file: "10"

#   toolbox-nginx:
#     image: nginx:alpine
#     container_name: api-toolbox-proxy.accutrak.dev
#     volumes:
#       - ./Infra/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
#     ports:
#       - "1950:80"
#     restart: always
#     depends_on:
#       - toolbox-api
#     networks:
#       - accutrak-network
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "50M"
#         max-file: "10"


  seedco-pd-db:
    container_name: pd-db
    hostname: pd-db
    image: postgres:14-alpine
    restart: unless-stopped
    networks:
      - seedco-network
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tomatoes123
      - POSTGRES_USER=toolbox_admin #postgres
      - POSTGRES_DB=seedco_pd

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    restart: always
    networks:
      - seedco-network
    ports:
      - "8777:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: justinpmsmith@outlook.com
      PGADMIN_DEFAULT_PASSWORD: mamelodishongos
    volumes:
      - pgadmin-data:/var/lib/pgadmin



