server {
    listen 80;

    location / {
        root /usr/share/nginx/html/uploads;
        autoindex on;
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
    }
}
